# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-09 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='h1_text',
            field=models.CharField(blank=True, default='Main head', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='h2_text',
            field=models.CharField(blank=True, default='Second head', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='header_bg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='logotype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
