# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-09 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('home', '0003_auto_20180209_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=30)),
                ('desc', models.TextField(blank=True, max_length=200)),
                ('skill_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
        ),
    ]
